version: '2'

services:
  # --------------
  # database
  # --------------
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: netflixusr
      MYSQL_PASSWORD: netflix123
      MYSQL_DATABASE: netflix

  # --------------
  # registry
  # --------------
  discovery:
    image: 1tiquinho/startupone:discovery1.0
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # --------------
  # zuul proxy
  # --------------
  zuul:
    image: 1tiquinho/startupone:zuul2.0
    ports:
      - "80:8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # --------------
  # clientes
  # --------------
  clientes:
    image: 1tiquinho/startupone:clientes2.0
    ports:
      - "8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # --------------
  # filmes
  # --------------
  filmes:
    image: 1tiquinho/startupone:filmes2.0
    ports:
      - "8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker


